name: Docker Image CI

on:
  push:
    branches: 
      - master
      - "5.0"
  pull_request:
    branches:
      - master
      - "5.0"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set environment for branch
      run: |
        if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
            echo "TAG=latest" >> "$GITHUB_ENV"
        fi
        if [[ $GITHUB_REF == 'refs/heads/5.0' ]]; then
            echo "TAG=5" >> "$GITHUB_ENV"
        fi
    - uses: actions/checkout@v2
    
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/jdenda/docker-cura:${{$TAG}}
        docker push ghcr.io/jdenda/docker-cura:${{$TAG}}
