name: Docker Image CI

on:
  push:
    branches:
      - master
      - dev
      - "5.0"
  pull_request:
    branches:
      - master
      - "5.0"
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment for branch
        id: branch_check
        run: |
          if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
              echo "::set-output name=env_name::latest"
          fi
          if [[ $GITHUB_REF == 'refs/heads/5.0' ]]; then
              echo "::set-output name=env_name::cura5"
          fi
          if [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
              echo "::set-output name=env_name::dev"
          fi

      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag 'ghcr.io/jdenda/docker-cura:${{ steps.branch_check.outputs.env_name }}'
          docker push 'ghcr.io/jdenda/docker-cura:${{ steps.branch_check.outputs.env_name }}'
